language: java

dist: trusty

addons:
  sonarcloud:
    organization: "sidexrus"
    token:
      secure: "3bab2a7efeccb981f7a6d43ed81955c96190980a" # encrypted value of your token

script: 
- mvn -q -B -f consoleInterface/pom.xml clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=sidexrus_Application-launch-control
- mvn -q -B -f clientD/pom.xml clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=sidexrus_Application-launch-control
